"""Local, deterministic security intelligence. No network clients or external AI."""
ASSET = {"id": "asset-fintrust", "name": "FinTrust Customer Portal", "url": "https://portal.fintrust-demo.local", "environment": "Production", "exposure": "Internet-facing", "type": "Web Application", "status": "Active", "owner": "Digital Banking Team", "criticality": "High"}
DISCLAIMER = "CyberGuard AI MVP uses deterministic demonstration assessment data. Findings shown in this demonstration represent a simulated security assessment intended to demonstrate vulnerability management, contextual risk prioritization, correlation, remediation and reporting workflows."
STAGES = ["Initializing Assessment", "Asset Discovery", "HTTP Configuration Analysis", "Application Exposure Analysis", "Security Controls Review", "Vulnerability Correlation", "Contextual Risk Analysis", "AI-Assisted Analysis", "Building Attack Paths", "Generating Results"]

# Baseline + applicable, visible context factors. Final scores are bounded to 0–100.
def risk_score(finding):
    factors = [{"label": "Severity baseline", "value": {"CRITICAL": 55, "HIGH": 59, "MEDIUM": 33, "LOW": 13}[finding["severity"]]}, {"label": "Internet-facing exposure", "value": 8}, {"label": "High business criticality", "value": 5}, {"label": "Confidence adjustment", "value": 5 if finding["confidence"] >= 95 else 2}]
    if finding["id"] == "CG-F002": factors[0]["value"] = 57
    if finding["id"] == "CG-F003": factors[0]["value"] = 60
    if finding["id"] == "CG-F004": factors[0]["value"] = 63
    if finding["id"] == "CG-F001": factors.append({"label": "Credential exposure", "value": 15})
    if finding["path"]: factors.append({"label": "Attack path participation", "value": 8})
    if finding["related"]: factors.append({"label": "Related finding correlation", "value": 3 if finding["severity"] == "HIGH" else 0})
    return min(100, sum(f["value"] for f in factors)), [f for f in factors if f["value"]]

def make_finding(n, title, severity, cwe, confidence, category, resource, description, evidence, technical, business, remediation, related=None, path=None, cvss=0, status="OPEN"):
    f = dict(id=f"CG-F{n:03d}", title=title, severity=severity, cwe=cwe, confidence=confidence, category=category, resource=resource, description=description, evidence=evidence, technical_impact=technical, business_impact=business, remediation=remediation, related=related or [], path=path, cvss=cvss, status=status, asset=ASSET["name"], first_detected="2026-08-20T09:00:00Z", last_detected="2026-09-10T09:00:00Z")
    f["risk"], f["factors"] = risk_score(f)
    f["priority"] = "P1 · Immediate" if f["risk"] >= 90 else "P2 · Within 7 days" if f["risk"] >= 75 else "P3 · Within 30 days" if f["risk"] >= 40 else "P4 · Next maintenance"
    return f

FINDINGS = [
make_finding(1, "Exposed API Credential in Public Source Map", "CRITICAL", "CWE-798", 98, "Credential Exposure", "/assets/app.js.map", "A fictional API credential is embedded in a production source-map artifact. Public access to this artifact illustrates how build-time secrets can reach client-side delivery.", "DEMO_API_KEY=CG_DEMO_NOT_REAL_2026\nSource: /assets/app.js.map · sourcesContent[3]\nFictional demonstration credential — not a real secret.", "If a real, valid credential were exposed in this way, a visitor could extract it and potentially access API operations within its assigned permissions. No credential was tested and no API access occurred.", "A similar exposure in a banking application could put customer information and service integrity at risk, creating incident-response costs and a loss of customer trust.", ["Revoke and rotate the exposed demo credential in the scenario; verify that the old value is invalid.", "Remove credentials from browser bundles and source maps. Keep secrets in server-side configuration.", "Disable public production source maps and purge affected build artifacts from caches.", "Review scoped API access logs and add secret checks to the build pipeline."], ["CG-F002"], "AP-001", 9.1),
make_finding(2, "Publicly Accessible Source Map", "HIGH", "CWE-200", 97, "Information Disclosure", "/assets/app.js.map", "The simulated production build publishes a source map containing original source names and application logic.", "GET /assets/app.js.map → simulated 200 OK\nContent-Type: application/json\nsources: [src/api/client.ts, src/config.ts]", "Source reconstruction could reveal internal routes and sensitive implementation details, helping an attacker focus subsequent attempts.", "Leaked implementation details can lower the effort needed to identify weaknesses in customer-facing services.", ["Exclude source maps from publicly served production artifacts.", "Upload debugging maps only to a private, access-controlled error tracking service.", "Verify the public path no longer serves the map after deployment."], ["CG-F001"], "AP-001", 7.5),
make_finding(3, "Missing Content Security Policy", "HIGH", "CWE-693", 96, "Security Headers", "/", "The demonstration response does not include a Content-Security-Policy header.", "Simulated response header review\nContent-Security-Policy: [absent]", "Without a restrictive policy, a separate injection weakness could have a wider impact. The missing header alone does not prove cross-site scripting.", "Weaker browser defenses could increase the impact of a future content-injection issue on customer sessions.", ["Inventory the application's required script and connection origins.", "Test a restrictive nonce-based policy in report-only mode.", "Enforce the policy after validating critical customer workflows."], ["CG-F004"], None, 7.1),
make_finding(4, "Session Cookie Missing HttpOnly Flag", "HIGH", "CWE-1004", 98, "Session Security", "/auth/session", "The fictional session cookie lacks HttpOnly, allowing JavaScript to read the cookie in the browser.", "Set-Cookie: demo_session=FICTIONAL_SESSION; Secure; SameSite=Lax\nHttpOnly: [absent]", "If script execution were obtained through another weakness, the session value might be readable. No session was stolen.", "A combined weakness could affect account confidentiality and require customer session invalidation.", ["Set HttpOnly and Secure on every session cookie.", "Retain an appropriate SameSite policy and rotate session IDs after login.", "Test authentication and sign-out behavior after the change."], ["CG-F003"], None, 7.5),
make_finding(5, "Server Version Disclosure", "MEDIUM", "CWE-200", 95, "Information Disclosure", "/", "A fictional server banner advertises an implementation version.", "Server: DemoWeb/1.4.2 (fictional)", "Detailed banners can help an observer select relevant attack hypotheses; they do not establish an exploitable version.", "Unnecessary disclosure adds reconnaissance value without improving the customer experience.", ["Remove detailed version tokens from public response headers.", "Keep the underlying server patched independently of banner changes."], [], None, 5.3),
make_finding(6, "Missing X-Frame-Options", "MEDIUM", "CWE-1021", 96, "Security Headers", "/account", "The account page has no demonstrated framing restriction.", "X-Frame-Options: [absent]\nCSP frame-ancestors: [absent]", "A third-party page might embed sensitive UI for clickjacking if no alternative framing protection is present.", "Misleading embedded interfaces could cause customers to make unintended actions.", ["Set CSP frame-ancestors to 'none' or an approved allowlist.", "Use X-Frame-Options: DENY as a compatible fallback.", "Confirm sensitive pages cannot be framed by an untrusted origin."], [], None, 5.4),
make_finding(7, "Missing Referrer-Policy", "MEDIUM", "CWE-200", 93, "Security Headers", "/account/overview", "The simulated response does not explicitly control referrer information.", "Referrer-Policy: [absent]", "Depending on browser defaults and navigation context, URL information may be sent in referrer metadata.", "Explicit policy reduces accidental disclosure of sensitive navigation context to other sites.", ["Set Referrer-Policy: strict-origin-when-cross-origin or a stricter policy.", "Do not put customer identifiers or secrets in URL query strings."], [], None, 4.3),
make_finding(8, "Public Debug Configuration Endpoint", "MEDIUM", "CWE-215", 97, "Misconfiguration", "/debug/config", "A fictional debug endpoint describes feature flags and internal service names.", "GET /debug/config → simulated 200 OK\nmode: demo-debug\nservice: fictional-ledger-api\nNo real internal addresses or secrets.", "Debug metadata could expose application structure and complement technology-stack disclosure.", "Unnecessary operational detail can increase the ease of reconnaissance against business services.", ["Disable debug routes in production builds.", "Restrict any necessary diagnostics to authenticated administrative access.", "Add a deployment check confirming public debug routes are unavailable."], ["CG-F010"], "AP-002", 5.3),
make_finding(9, "Missing Permissions-Policy", "LOW", "CWE-693", 91, "Security Headers", "/", "The application does not declare a browser feature permissions policy.", "Permissions-Policy: [absent]", "Browser features remain governed by defaults instead of a deliberate application-level restriction.", "Reducing unused browser capabilities improves defense in depth with limited implementation effort.", ["Disable unused browser features, such as camera, microphone and geolocation, through Permissions-Policy.", "Validate any customer workflow that needs an allowed feature."], [], None, 3.1),
make_finding(10, "Technology Stack Disclosure", "LOW", "CWE-200", 92, "Information Disclosure", "/assets/app.js", "Public build metadata identifies a fictional frontend framework and component names.", "X-Powered-By: DemoFramework\nBuild metadata: fictional-client-v2", "Technology details can combine with debug metadata to form a more complete application profile.", "This low-severity exposure becomes more useful to an observer when paired with other information leaks.", ["Remove unnecessary framework-identifying headers and debug build metadata.", "Keep dependencies maintained; hiding a framework is not a substitute for patching."], ["CG-F008"], "AP-002", 3.1),
make_finding(11, "Missing X-Content-Type-Options", "LOW", "CWE-693", 99, "Security Headers", "/", "Previously missing MIME-sniffing protection was corrected in the historical demonstration.", "X-Content-Type-Options: nosniff\nVerified in the 10 September demonstration fixture.", "The current simulated response prevents MIME sniffing through the nosniff header.", "This completed hardening task demonstrates measurable progress in the security program.", ["Keep X-Content-Type-Options: nosniff enabled.", "Include the header in deployment regression checks."], [], None, 3.1, "RESOLVED")]

PATHS = [dict(id="AP-001", title="From public artifact to potential API access", severity="CRITICAL", score=96, findings=["CG-F002", "CG-F001"], nodes=["Public Source Map Exposure", "Application Information Disclosure", "Exposed Demo API Credential", "Potential Unauthorized API Access"], explanation="A publicly available source map could reveal application code and a credential. If a real credential were valid and sufficiently privileged, it could enable unauthorized API access. This is a correlated possibility, not observed exploitation.", fix_order=["Rotate the exposed credential", "Remove secrets from client artifacts", "Disable public source maps", "Review API permissions and access logs"]), dict(id="AP-002", title="Disclosure expands application intelligence", severity="MEDIUM", score=59, findings=["CG-F010", "CG-F008"], nodes=["Technology Stack Disclosure", "Debug Configuration Exposure", "Expanded Application Intelligence"], explanation="Technology metadata and a debug configuration can be combined to infer application structure. This chain demonstrates reconnaissance value; it does not establish a compromise.", fix_order=["Disable public debug endpoints", "Remove framework and version metadata", "Verify production build settings"])]

def analysis(f, asset=ASSET):
    correlation = "It participates in a potential exposure chain; fixing it also interrupts related risk." if f["path"] else "Treat this as a defense-in-depth issue in the context of the related application controls."
    return [{"title": "Why This Matters", "body": f"This {f['severity'].lower()} {f['category'].lower()} finding has contextual risk {f['risk']}/100 and {f['confidence']}% fixture confidence. The {asset['exposure'].lower()}, {asset['criticality'].lower()}-criticality asset increases its priority. {correlation}"}, {"title": "Technical Impact", "body": f["technical_impact"]}, {"title": "Business Impact", "body": f["business_impact"]}, {"title": "Recommended Action", "body": f["remediation"][0]}, {"title": "Remediation Priority", "body": f["priority"] + ". Validate the change in a subsequent assessment; a new simulated scan alone does not constitute remediation."}, {"title": "Related Risk", "body": ("Review " + ", ".join(f["related"]) + ". " if f["related"] else "No direct correlated finding in this dataset. ") + correlation}]

QUESTIONS = ["What should we fix first?", "Explain our biggest risk.", "Summarize the current security posture.", "What is the top potential attack path?", "Create a remediation plan.", "Explain these findings to management."]

def analyst(question, findings, score, paths):
    opened = sorted([f for f in findings if f["status"] == "OPEN"], key=lambda f: -f["risk"])
    if not opened: return {"title": "No open findings", "intro": "All findings have a disposition. Verify remediation independently before treating accepted or false-positive findings as fixed.", "sections": []}
    top = opened[0]
    priorities = [{"title": f"{i+1:02d} · {f['title']}", "body": f"{f['priority']} · Risk {f['risk']}/100. {f['remediation'][0]} {('Interrupts ' + f['path'] + '.') if f['path'] else 'Strengthens the application security baseline.'}"} for i, f in enumerate(opened[:5])]
    if question in (QUESTIONS[0], QUESTIONS[4]):
        return {"title": "Your prioritized remediation plan", "intro": f"Start with {top['title'].lower()}. Priorities combine severity, exposure, business criticality, confidence and correlation; they are not simply a list of scanner alerts.", "sections": priorities}
    if question == QUESTIONS[1]: return {"title": "The highest-priority exposure", "intro": top["title"], "sections": analysis(top)}
    if question == QUESTIONS[3]:
        path = paths[0] if paths else None
        return {"title": "The leading potential attack path", "intro": path["explanation"] if path else "No active path is supported by the current open findings.", "sections": [{"title": "Possible exposure chain", "body": " → ".join(path["nodes"])}, {"title": "Recommended fix order", "body": " → ".join(path["fix_order"])}] if path else []}
    return {"title": "Security posture, explained clearly", "intro": f"FinTrust's latest completed assessment has a benchmark score of {score}/100. There are {len(opened)} open findings, including {sum(f['severity']=='CRITICAL' for f in opened)} critical. The latest score describes the assessment snapshot, while dispositions reflect the current triage state.", "sections": [{"title": "Business exposure", "body": top["business_impact"]}, {"title": "Progress and next steps", "body": "The seeded benchmark improved from 51 to 58 as security controls matured. Prioritize credential handling, public build artifacts and browser/session controls; assign the Digital Banking Team to verify each fix."}, {"title": "Decision for management", "body": "Schedule immediate containment of the highest-risk exposure and a seven-day hardening sprint. Track verified remediation separately from accepted risk. These results are simulated and are not evidence of a real compromise."}]}
